# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LSP <- function(x, J = 1L) {
    .Call(`_carelessonset_LSP`, x, J)
}

Tn_multivariate <- function(x, theta) {
    .Call(`_carelessonset_Tn_multivariate`, x, theta)
}

rcpp_hello_world <- function() {
    .Call(`_carelessonset_rcpp_hello_world`)
}

mean_ab_cpp <- function(x, start, stop) {
    .Call(`_carelessonset_mean_ab_cpp`, x, start, stop)
}

Tn_univariate <- function(x, theta) {
    .Call(`_carelessonset_Tn_univariate`, x, theta)
}

